"""empty message

Revision ID: b69d1cac80cd
Revises:
Create Date: 2023-10-29 18:53:24.044005

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b69d1cac80cd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "popugs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("beak_size", sa.Integer(), nullable=True),
        sa.Column("account", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("beak_size"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("popugs")
    # ### end Alembic commands ###
